### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by mutalisk999**
- Remove pdm.lock
- Add pdm.lock to .gitignore
- Fix typo

### CODE REVIEW

**Comment by andyzhouty** [comment]
According to [gitignore/Python.gitignore L105](https://github.com/github/gitignore/blob/d0b80a469983a7beece8fa1f5c48a8242318b531/Python.gitignore#L105), I don't think pdm.lock should be added to .gitignore.

**Comment by rice0208** [comment]
Woohoo~ First PR, but I don't think pdm.lock should be deleted.

**Review by andyzhouty — CHANGES_REQUESTED** [review]
Just keep the pdm.lock

**Comment by mutalisk999** [comment]
Okay keep it.

**Comment by rice0208** [comment]
sounds good. Merge.

**Pull request merged**
